### ISSUE TITLE
Malfunctioning Code

### ISSUE THREAD

**Issue by joaquin-sarmiento** [GerrySoft/GerryVideos#1]
These are the errors:

![errors](https://user-images.githubusercontent.com/58922125/99412064-162a1800-28d3-11eb-92bd-0810c94efa3b.png)

Thanks!

**Comment by gerardet46** [comment]
Which version of C++ and compiler are you using?

It should work (at least) on GCC and Visual C++ for C++ 11 or later

**Comment by Alex1344neti** [comment]
Hola, vi tu video de corrección de errores pero aún así me muestra los siguientes errores, espero puedas ayudarme. Estoy usando Visual Studio 2019:
![Captura de pantalla (72)](https://user-images.githubusercontent.com/78002825/105867385-a6af6380-5fba-11eb-8d44-5c5e160e6fe1.png)
Gracias!!!

**Comment by gerardet46** [comment]
Hola, ese error no es del código. A veces cuando se copia y pega código sin más a visual studio salta el error de "símbolo externo sin resolver". Mira de crear un proyecto vacío de C++ e ir copiando y pegando a los archivos. Ten en cuenta que en la carpeta de este repositorio no hay un "proyecto", sinó que simplemente están los archivos

**Comment by gerardet46** [comment]
Cerrado por inactividad
