### ISSUE TITLE
Es posible subir el sln de capturar datos de una web?

### ISSUE THREAD

**Issue by MiClobiMC** [GerrySoft/GerryVideos#2]
Se agradeceria mucho

**Comment by gerardet46** [comment]
Lo siento pero nunca conservo estos proyectos para mantener una organización en el ordenador. En realidad aquí la intención es solo subir el código fuente, ya que estos tutoriales no estan enfocados a copiar-pegar, sinó a aprender, y estos códigos que subo sirven de guía.
De nuevo, lo siento pero ya no tengo este proyecto
